"""
B-Rep export functions: STL export from CadQuery geometry.

Reuses mesh extraction from brep_preview.py for consistency.
"""

from __future__ import annotations

import struct
import sys
from pathlib import Path
from typing import Optional

import numpy as np

# Ensure agent directory is on path for imports
_agent_dir = Path(__file__).resolve().parent
if str(_agent_dir) not in sys.path:
    sys.path.insert(0, str(_agent_dir))

from brep_preview import get_mesh_json


def export_stl(code: str, tolerance: float = 0.1) -> bytes:
    """
    Export CadQuery code to binary STL format.

    Args:
        code: CadQuery Python code with 'result' variable
        tolerance: Mesh tessellation tolerance in mm

    Returns:
        Binary STL data (bytes)

    Raises:
        ValueError: If code execution or mesh extraction fails
    """
    mesh_data = get_mesh_json(code, tolerance)

    vertices = mesh_data["vertices"]
    faces = mesh_data["faces"]

    if not vertices or not faces:
        raise ValueError("Mesh is empty - no geometry to export")

    return _write_binary_stl(vertices, faces)


def _write_binary_stl(vertices: list[list[float]], faces: list[list[int]]) -> bytes:
    """
    Write mesh to binary STL format.

    Binary STL format:
    - 80 byte header
    - 4 byte uint32: number of triangles
    - For each triangle:
        - 12 bytes: normal vector (3 x float32)
        - 36 bytes: 3 vertices (3 x 3 x float32)
        - 2 bytes: attribute byte count (usually 0)
    """
    # Create output buffer
    output = bytearray()

    # 80-byte header (can be anything, usually zeros or description)
    header = b"Binary STL generated by SketchCAD B-Rep Agent" + b"\0" * 35
    output.extend(header[:80])

    # Number of triangles
    n_triangles = len(faces)
    output.extend(struct.pack("<I", n_triangles))

    # Compute normals for each face
    normals = _compute_face_normals(vertices, faces)

    # Write each triangle
    for i, face in enumerate(faces):
        # Normal vector
        nx, ny, nz = normals[i]
        output.extend(struct.pack("<fff", nx, ny, nz))

        # Three vertices
        for idx in face:
            x, y, z = vertices[idx]
            output.extend(struct.pack("<fff", x, y, z))

        # Attribute byte count (unused, set to 0)
        output.extend(struct.pack("<H", 0))

    return bytes(output)


def _compute_face_normals(vertices: list[list[float]], faces: list[list[int]]) -> list[tuple[float, float, float]]:
    """
    Compute face normals for STL output.

    Returns list of (nx, ny, nz) tuples for each face.
    """
    import math

    normals = []

    for face in faces:
        if len(face) < 3:
            normals.append((0.0, 0.0, 1.0))
            continue

        v0 = vertices[face[0]]
        v1 = vertices[face[1]]
        v2 = vertices[face[2]]

        # Edge vectors
        e1 = [v1[0] - v0[0], v1[1] - v0[1], v1[2] - v0[2]]
        e2 = [v2[0] - v0[0], v2[1] - v0[1], v2[2] - v0[2]]

        # Cross product
        nx = e1[1] * e2[2] - e1[2] * e2[1]
        ny = e1[2] * e2[0] - e1[0] * e2[2]
        nz = e1[0] * e2[1] - e1[1] * e2[0]

        # Normalize
        length = math.sqrt(nx * nx + ny * ny + nz * nz)
        if length > 0:
            nx /= length
            ny /= length
            nz /= length
        else:
            nx, ny, nz = 0.0, 0.0, 1.0

        normals.append((nx, ny, nz))

    return normals


def get_mesh_for_preview(code: str, tolerance: float = 0.1) -> dict:
    """
    Get mesh data for browser preview.

    This is a convenience function that wraps get_mesh_json.

    Args:
        code: CadQuery Python code
        tolerance: Mesh tessellation tolerance

    Returns:
        Mesh JSON dict
    """
    return get_mesh_json(code, tolerance)


# =============================================================================
# Optional: Trimesh-based export (more accurate)
# =============================================================================

def export_stl_trimesh(code: str, tolerance: float = 0.1) -> bytes:
    """
    Export to STL using trimesh library (more accurate normals, mesh repair).

    Falls back to manual export if trimesh not available.
    """
    try:
        import trimesh

        mesh_data = get_mesh_json(code, tolerance)

        v = np.array(mesh_data["vertices"], dtype=np.float64)
        f = np.array(mesh_data["faces"], dtype=np.int64)

        mesh = trimesh.Trimesh(vertices=v, faces=f)

        # Optional: Fix mesh issues
        mesh.fix_normals()

        return mesh.export(file_type="stl")

    except ImportError:
        # Fall back to manual export
        return export_stl(code, tolerance)